### ISSUE TITLE
Getting the full document using a selector

### ISSUE THREAD

**Issue by ChadSikorra** [klkvsk/json-decode-stream#1]
First off, thanks for creating this library. It's exactly what I'm looking for to be able to parse JSON objects coming in over a stream in an unpredictable order.

My question is regarding how do I retrieve the full JSON document using a selector? Is it only possible to use the `[]` selector and then just construct the full document yourself using the key / value pairs? My current solution is this (crude example...):

```php
use JsonDecodeStream\Event;

$parser = Parser::fromString($json);

foreach ($parser->events() as $event) {
    if ($event->getId() === Event::DOCUMENT_END) {
        $data = [];

        foreach ($parser->items('[]', true) as $key => $item) {
            $data[$key] = $item;
        }
        
        // complete document here...
        var_dump($data);
    }
}
```

**Comment by klkvsk** [comment]
Hello!
As I understood, you're speaking of JSON sequences, which I forgot to test. Turns out, it needed a more relaxed arguments input for items()/Collector() to allow null as selector too.

So, to collect whole objects in a sequence of objects separated by coma or/and newline, you should just call `$parser->items()`. See tests in a commit above for an example.

Pushed v1.0.1 with this fix.

Of course, it should be noted, if parsing a single large JSON this way, there would be no benefits over using `json_decode` since the collector would keep whole structure in memory until returned.

**Comment by ChadSikorra** [comment]
Thanks @klkvsk ! That's exactly what I was looking for. My current use case is that I'm receiving streamed JSON objects over a PSR-7 `StreamInterface`. This change makes it very easy to iterate over these objects as they arrive in the stream.

I can confirm that this works on my end too, and makes the code look much cleaner. Thanks again.
